### ISSUE TITLE
Missing semicolons in app_main

### ISSUE THREAD

**Issue by GeorgeGRz** [DavidAntliff/esp32-i2c-lcd1602-example#1]
Hello, I was trying to build the source using `make flash monitor` and there was a typo at lines **141** and **169** in **app_main**.

**Comment by DavidAntliff** [comment]
Thanks for reporting - looks like the ESP_LOGx macros changed somewhere between ESP-IDF v3.0 and v3.3 to not include a terminating `;`, resulting in this typo causing a compile error with v3.3. I've fixed this in ec1adab.
