### ISSUE TITLE
Components missing from source code download

### ISSUE THREAD

**Issue by norlesh** [DavidAntliff/esp32-i2c-lcd1602-example#5]
FYI when the project is downloaded and unzipped from github through the website interface the build fails because the esp32-i2c-lcd1602 and esp32-smbus directories are empty.

**Comment by DavidAntliff** [comment]
@norlesh thank you for letting me know. This is actually an issue with GitHub and unfortunately there's very little I can do about it: https://github.com/dear-github/dear-github/issues/214. Best option is to use `git` to get a complete source tree.
